### ISSUE TITLE
 No view found for id 0x7f080045 (com.ncapdevi.sample:id/container) for fragment RecentsFragment

### ISSUE THREAD

**Issue by suhask** [ncapdevi/FragNav#105]
When I try to include my root fragments inside the container fragment i get the following error.
But it works fine when i try to include my root fragments inside activity.

12-16 13:15:28.710 21006-21006/com.ncapdevi.sample E/FragmentManager: No view found for id 0x7f080045 (com.ncapdevi.sample:id/container) for fragment RecentsFragment{2bc7bf3 #1 id=0x7f080045 com.ncapdevi.sample.fragments.RecentsFragment1}
12-16 13:15:28.710 21006-21006/com.ncapdevi.sample E/FragmentManager: Activity state:
12-16 13:15:28.720 21006-21006/com.ncapdevi.sample E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.ncapdevi.sample, PID: 21006
                                                                     java.lang.RuntimeException: Unable to resume activity {com.ncapdevi.sample/com.ncapdevi.sample.activities.TestActivity}: java.lang.IllegalArgumentException: No view found for id 0x7f080045 (com.ncapdevi.sample:id/container) for fragment RecentsFragment{2bc7bf3 #1 id=0x7f080045 com.ncapdevi.sample.fragments.RecentsFragment1}
                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4155)
                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4245)
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3360)
                                                                         at android.app.ActivityThread.access$1100(ActivityThread.java:221)
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794)
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                         at android.os.Looper.loop(Looper.java:158)
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7224)
                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                                      Caused by: java.lang.IllegalArgumentException: No view found for id 0x7f080045 (com.ncapdevi.sample:id/container) for fragment RecentsFragment{2bc7bf3 #1 id=0x7f080045 com.ncapdevi.sample.fragments.RecentsFragment1}
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1413)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1740)
                                                                         at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1809)
                                                                         at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:799)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2580)
                                                                         at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2367)
                                                                         at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2322)
                                                                         at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2229)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3221)
                                                                         at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:3181)
                                                                         at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:214)
                                                                         at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:470)
                                                                         at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:459)
                                                                         at android.app.Activity.performResume(Activity.java:7016)
                                                                         at android.app.ActivityThread.performResumeActivity(ActivityThread.java:4144)
                                                                         at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:4245) 
                                                                         at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3360) 
                                                                         at android.app.ActivityThread.access$1100(ActivityThread.java:221) 
                                                                         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1794) 
                                                                         at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                         at android.os.Looper.loop(Looper.java:158) 
                                                                         at android.app.ActivityThread.main(ActivityThread.java:7224) 
                                                                         at java.lang.reflect.Method.invoke(Native Method) 
                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230) 
                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

**Comment by ncapdevi** [comment]
Looks like you're passing in the wrong view ID, doesn't sound like a problem with the library
