### ISSUE TITLE
Fragment already added

### ISSUE THREAD

**Issue by itzharDev** [ncapdevi/FragNav#119]
unknown scenario:

```
java.lang.IllegalStateException: Fragment already added: HomeFragment{b501609 #1 id=0x7f080087 activities.main.home.HomeFragment3}
at android.support.v4.app.FragmentManagerImpl.attachFragment(FragmentManager.java:1982)
at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:780)
at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2590)
at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2377)
at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2332)
at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2239)
at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:700)
at android.os.Handler.handleCallback(Handler.java:815)
at android.os.Handler.dispatchMessage(Handler.java:104)
at android.os.Looper.loop(Looper.java:207)
at android.app.ActivityThread.main(ActivityThread.java:5765)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)
```

**Comment by ncapdevi** [comment]
Seems like you're adding the same instance of a fragment twice. You'll need a new instance for ever push
