### ISSUE TITLE
Crash on `replaceFragment`

### ISSUE THREAD

**Issue by DanteAndroid** [ncapdevi/FragNav#54]
Work:
        `fragNavController.pushFragment(f);`
Not work:
     `fragNavController.replaceFragment(f);`

Crash Log:
```
03-15 15:29:59.557 10878-10878/com.dante.diary E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.dante.diary, PID: 10878
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                     at android.support.v4.app.FragmentTransitionCompat21.captureTransitioningViews(FragmentTransitionCompat21.java:364)
                                                                     at android.support.v4.app.FragmentTransition.configureEnteringExitingViews(FragmentTransition.java:901)
                                                                     at android.support.v4.app.FragmentTransition.access$100(FragmentTransition.java:37)
                                                                     at android.support.v4.app.FragmentTransition$2.run(FragmentTransition.java:367)
                                                                     at android.support.v4.app.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:64)
                                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```
 
Thx!

**Comment by ncapdevi** [comment]
Hey there, sorry for a bit of the delay. I'm not sure why this would be happening. Can you supply a bit more code that's causing this to happen? All of the stacktrace here would be outside of FragNav's scope

**Comment by DanteAndroid** [comment]
```
03-21 13:19:13.487 2025-32125/com.google.android.googlequicksearchbox:search W/CronetSyncConnectionRcs: Upload content type not set.
03-21 13:19:15.622 31736-31865/com.dante.diary E/Surface: getSlotFromBufferLocked: unknown buffer: 0xa2b32e00
03-21 13:19:17.088 31736-31736/com.dante.diary I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-21 13:19:17.100 31736-31736/com.dante.diary I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-21 13:19:17.100 31736-31736/com.dante.diary I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-21 13:19:17.101 31736-31736/com.dante.diary I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-21 13:19:17.103 31736-31736/com.dante.diary I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-21 13:19:17.109 31736-31736/com.dante.diary I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-21 13:19:17.109 31736-31736/com.dante.diary I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-21 13:19:17.110 31736-31736/com.dante.diary I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-21 13:19:17.111 31736-31736/com.dante.diary I/AppCompatViewInflater: app:theme is now deprecated. Please move to using android:theme instead.
03-21 13:19:17.113 31736-31736/com.dante.diary I/TextInputLayout: EditText added is not a TextInputEditText. Please switch to using that class instead.
03-21 13:19:17.114 1257-1629/? D/AudioFlinger: mixer(0xb4540000) throttle end: throttle time(55)
03-21 13:19:17.138 31736-31736/com.dante.diary D/ProfileFragment: gogo100158434  
03-21 13:19:17.158 31736-31736/com.dante.diary D/AndroidRuntime: Shutting down VM
                                                                 
                                                                 
                                                                 --------- beginning of crash
03-21 13:19:17.241 31736-31736/com.dante.diary E/AndroidRuntime: FATAL EXCEPTION: main
                                                                 Process: com.dante.diary, PID: 31736
                                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
                                                                     at android.support.v4.app.FragmentTransitionCompat21.captureTransitioningViews(FragmentTransitionCompat21.java:364)
                                                                     at android.support.v4.app.FragmentTransition.configureEnteringExitingViews(FragmentTransition.java:901)
                                                                     at android.support.v4.app.FragmentTransition.access$100(FragmentTransition.java:37)
                                                                     at android.support.v4.app.FragmentTransition$2.run(FragmentTransition.java:367)
                                                                     at android.support.v4.app.OneShotPreDrawListener.onPreDraw(OneShotPreDrawListener.java:64)
                                                                     at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:944)
                                                                     at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2055)
                                                                     at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1107)
                                                                     at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6013)
                                                                     at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
                                                                     at android.view.Choreographer.doCallbacks(Choreographer.java:670)
                                                                     at android.view.Choreographer.doFrame(Choreographer.java:606)
                                                                     at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
                                                                     at android.os.Handler.handleCallback(Handler.java:739)
                                                                     at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                     at android.os.Looper.loop(Looper.java:148)
                                                                     at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                 
                                                                 
                                                                 --------- beginning of system
03-21 13:19:17.241 1563-1999/system_process W/ActivityManager:   Force finishing activity com.dante.diary/.main.MainActivity
03-21 13:19:17.247 1563-32244/system_process W/DropBoxManagerService: Dropping: data_app_crash (1777 > 0 bytes)
03-21 13:19:17.265 1241-1241/? E/EGL_emulation: tid 1241: eglCreateSyncKHR(1315): error 0x3004 (EGL_BAD_ATTRIBUTE)
03-21 13:19:17.313 1563-1610/system_process I/OpenGLRenderer: Initialized EGL, version 1.4
03-21 13:19:17.321 2216-32245/com.google.android.gms D/DropBoxEntryAddedChimeraService: User is not opted-in to Usage & Diagnostics.
03-21 13:19:17.782 1563-1577/system_process W/ActivityManager: Activity pause timeout for ActivityRecord{8e2fb60 u0 com.dante.diary/.main.MainActivity t2096 f}
03-21 13:19:18.337 1910-2184/com.google.android.googlequicksearchbox W/OpenGLRenderer: Incorrectly called buildLayer on View: em, destroying layer...
03-21 13:19:18.337 1910-2184/com.google.android.googlequicksearchbox W/OpenGLRenderer: Incorrectly called buildLayer on View: em, destroying layer...

```

That's all for triggering the code. 
Code (in one of the root fragment of BottomBarActivity):
```
        activity.getSupportFragmentManager()
                .beginTransaction()
                .detach(this)
                .add(R.id.container, ProfileFragment.newInstance(id))
                .commit();  //Crash exactly like `replaceFragment`

OR

        activity.getSupportFragmentManager()
                .beginTransaction()
                .replace(R.id.container, ProfileFragment.newInstance(id))
                .commit();  //Crash exactly like `replaceFragment`

OR

activity.controller.replaceFragment(ProfileFragment.newInstance(id));
```
Seem like when I change the root fragment, it crashes. When push or add fragment, it works.

**Comment by DanteAndroid** [comment]
Oh, I forget one thing, the code happens in `onActivityCreated`

**Comment by ncapdevi** [comment]
So one thing when using this library, is that you should be using it for every fragment transaction (i.e., you should never be using activity.getSupportFragmentManager().beginTransaction()) .

Second, I'm not sure that this is a problem with the library.  According to this documentation https://developer.android.com/reference/android/app/Fragment.html#onActivityCreated(android.os.Bundle)  This only gauruntees the activity has been created, not that it has any views associcated with it yet.  Also The callstack has no references to FragNav, so it's not something with the library, it's something in the ordering that you're doing it.

Best of luck

**Comment by DanteAndroid** [comment]
Why should I not use getSupportFragmentManager().beginTransaction()? Cause I want to use custom animation, or other methods like add fragment. Could you please explain it?
And it doesn't make sense it crashes when I try to replace the root fragment. I think it possibly has sth to do with FragNav. Any idea?

**Comment by ncapdevi** [comment]
Yeah. So doing custom animations is supported in the latest version of the library that's currently in testing (2.0.0). Depending on which version of the library that you're compiling (assuming it's not the 2.0.0 version), I can totally see why you're trying to begin your own transactions as it was the only way to do some custom animations.  The problem with doing that is that it can theoretically mess with the tabs and backstacks. I'm not sure of all of the implications, but basically the library is designed such that you'll be performing all of the navigations with it's methods. Although, MAYBE it wouldn't cause a huge issue and could be used sparingly, I haven't given it a lot of thought.  You're right, you absolutely should be able to replace the root fragment.  

Although I'm not sure why it's exactly happening in your case. If you provide a test github repo or a PR to the sample app where I can replicate it, I might be able to track down the issue.
