### ISSUE TITLE
IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by stephanepechard** [ncapdevi/FragNav#96]
Hi and thanks for the lib,

I got a crash if I push or pop a fragment after an orientation change. Do I have anything to do to handle it? I save the state in the activity through `onSaveInstanceState`.

Here's the stack trace I got:
>   java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
     at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
     at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
     at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
     at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
     at com.ncapdevi.fragnav.FragNavController.commitTransaction(FragNavController.java:714)
     at com.ncapdevi.fragnav.FragNavController.clearStack(FragNavController.java:337)
     at com.ncapdevi.fragnav.FragNavController.popFragments(FragNavController.java:244)
     at com.ncapdevi.fragnav.FragNavController.popFragment(FragNavController.java:216)
     at com.ncapdevi.fragnav.FragNavController.popFragment(FragNavController.java:223)

**Comment by ncapdevi** [comment]
Hey @stephanepechard , could you give me a little more insight as to what action you're performing before this happens? Is this during `onCreate`?

**Comment by nealsanche** [comment]
This is also happening in my app, and I'm wondering how to work around it. My stacktrace is a little different.

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
	at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2054)
	at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2077)
	at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
	at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
	at com.ncapdevi.fragnav.FragNavController.switchTab(FragNavController.java:138)
	at com.ncapdevi.fragnav.FragNavController.switchTab(FragNavController.java:158)
	at co.uk.myapp.manage.presentation.main.NavControllerNavigator.pushFragment(NavControllerNavigator.kt:110)
	at co.uk.myapp.manage.app.managers.NavigationManager.pushFragment(NavigationManager.kt:20)
	at co.uk.myapp.manage.presentation.more.MoreFragment.showSettings(MoreFragment.kt:86)
	at co.uk.myapp.manage.presentation.more.MoreFragment$onViewCreated$1.onNavigationItemSelected(MoreFragment.kt:60)
	at android.support.design.widget.NavigationView$1.onMenuItemSelected(NavigationView.java:154)
	at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
	at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
	at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
	at android.support.design.internal.NavigationMenuPresenter$1.onClick(NavigationMenuPresenter.java:342)
	at android.view.View.performClick(View.java:6213)
	at android.view.View$PerformClick.run(View.java:23645)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```
So far I can't reproduce the issue at will, and really have no idea how the app is getting into this state. Still investigating.

**Comment by stephanepechard** [comment]
I don't work on the project where I got this error at the moment, so I can't help much. Hope to get more into it at the beginning of 2018...
Still, nice not to be the only one to hit it, we'll be some to investigate it.

**Comment by nealsanche** [comment]
I think this is not necessarily a problem with FragNav but instead a problem with trying to operate it when the app lifecycle isn't in the correct state. So far I've worked around it using some Android Architecture components Lifecycle helpers we've developed, and will wait to see if this actually fixes the problems we are seeing.

**Comment by gkonovalov** [comment]
Hi @ncapdevi,
Thank you for amazing library.
Unfortunately I have same error in my logs from crashlitics:

```
`Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2044)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2067)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:680)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:634)
       at com.ncapdevi.fragnav.FragNavController.commitTransaction(FragNavController.java:742)
       at com.ncapdevi.fragnav.FragNavController.switchTabInternal(FragNavController.java:217)
       at com.ncapdevi.fragnav.FragNavController.switchTab(FragNavController.java:192)
       at com.ncapdevi.fragnav.FragNavController.switchTab(FragNavController.java:240)
       at com.waverlylabs.pilot.speech.translator.ui.fragments.MainFragment.onTabSelected(MainFragment.java:62)
       at com.roughike.bottombar.BottomBar.updateSelectedTab(BottomBar.java:949)
       at com.roughike.bottombar.BottomBar.handleClick(BottomBar.java:926)
       at com.roughike.bottombar.BottomBar.onClick(BottomBar.java:893)
       at android.view.View.performClick(View.java:5230)
       at android.view.View$PerformClick.run(View.java:20999)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6117)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)`  
```

It's happen when I try to switch tabs:
 @Override
```
    public void onTabSelected(@IdRes int tabId) {
        switch (tabId) {
            case R.id.tabTranslate:
                navController.switchTab(TAB1);
                break;
            case R.id.tabEarpiece:
                navController.switchTab(TAB2);
                break;
        }
    }
```

Probably fix can be like this but I will need to test.
`  navController.switchTab(TAB1, FragNavTransactionOptions.newBuilder().allowStateLoss(true).build());`

**Comment by Kaz32** [comment]
Hi thanks for these lib,

I'm also got this error form crashlytics
`Caused by java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:2055)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:2078)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:678)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:632)
       at com.ncapdevi.fragnav.FragNavController.commitTransaction(FragNavController.java:742)
       at com.ncapdevi.fragnav.FragNavController.pushFragment(FragNavController.java:256)
       at com.ncapdevi.fragnav.FragNavController.pushFragment(FragNavController.java:273)
`


Any idea how to fix this, because I can't reproduce this error

Thanks

**Comment by ghost** [comment]
i have the same problem. i check the permission and if the permission denied i want to pop current fragment but i doesn't work.
