### ISSUE TITLE
java.lang.IllegalStateException: Fragment has not been attached yet.

### ISSUE THREAD

**Issue by itmanzzz** [ncapdevi/FragNav#99]
Dear Sir,

I have a problem when using your library:
-----
Caused by: java.lang.IllegalStateException: Fragment has not been attached yet.
                                                                                       at android.support.v4.app.Fragment.instantiateChildFragmentManager(Fragment.java:2210)
                                                                                       at android.support.v4.app.Fragment.getChildFragmentManager(Fragment.java:708)
                                                                                       at com.ncapdevi.fragnav.FragNavController.clearDialogFragment(FragNavController
------
In this case, 
Step1. I applied in my app and open it.
Step2. I click on Home button of the device to make it in the background.
Step 3. I'm using other apps 'Xender' and open scan feature.
Step 4. I came back to my app and its crashing.

Please help me.
Thanks,

**Comment by ncapdevi** [comment]
In this case, you are trying to perform an action with a fragment that hasn't been attached yet. Could you please try updating to the latest version of the library `2.3.0` and see if the issue persists? If it does, where are you performing the action?

**Comment by ncapdevi** [comment]
Without further information, I'm closing this issue
